name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose options
        required: true
        default: all_tests
        type: choice
        options:
          - all_tests
          - smoke_tests
          - non_smoke_tests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: setup Python
        uses: actions/setup-Python@v5
        with:
          python-version: "3.11"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run all_tests
        if: "github.event.inputs.deployment_target == 'all_tests'"
        run: pytest
      - name: Run smoke_tests
        if: "github.event.inputs.deployment_target == 'smoke_tests'"
        run: pytest -m smoke
      - name: Run not_smoke_tests
        if: "github.event.inputs.deployment_target == 'not_smoke_tests'"
        run: pytest -m 'not smoke'

